#!/bin/sh
xrandr --output DisplayPort-0 --off --output DisplayPort-1 --off --output DisplayPort-2 --mode 1366x768 --pos 2726x0 --rotate normal --output HDMI-A-0 --off --output DVI-D-0 --mode 1360x768 --pos 1366x0 --rotate normal
